SELECT v.IDATELIER, v.IDVACATION, a.NBPLACESMAXI, p.IDPARTICIPANT
FROM  VACATION v
INNER JOIN ATELIER a ON v.IDATELIER = a.ID
LEFT JOIN PARTICIPER p ON p.IDATELIER = v.IDATELIER AND p.IDVACATION = v.IDVACATION
