CREATE VIEW VATELIERVACATIONOCCUPES AS 
SELECT v.IDATELIER, v.IDVACATION, a.NBPLACESMAXI, COUNT(p.IDPARTICIPANT) AS NBPLACESOCCUPES 
FROM  VACATION v
INNER JOIN ATELIER a ON v.IDATELIER = a.ID
LEFT JOIN PARTICIPER p ON p.IDATELIER = v.IDATELIER AND p.IDVACATION = v.IDVACATION
GROUP BY v.IDATELIER, v.IDVACATION, a.NBPLACESMAXI
go