
USE PPE_M2L
go
-- TEST --

/*
INSERT PARTICIPANT (NOM, PRENOM, ADRESSE1, ADRESSE2, CP, VILLE, TEL, MAIL, DATEINSCRIPTION, DATEARRIVEE, CLEWIFI, TYPEPARTICIPANT, NUMEROLICENCE, DATENAISSANCEBENEVOLE, IDATELIERINTERVENANT, IDQUALITELICENCIE, IDSTATUT) 
VALUES (N'Sonntag', N'Christophe', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'Licencie', NULL, NULL, 1, NULL)
go

*/

/*
INSERT INTO [INSCRIRE] ( [IDATELIER] ,[IDPARTICIPANT] ) VALUES ( 1 , 1)
go
*/

/*
INSERT INTO [PARTICIPER] ( [IDATELIER] ,[IDVACATION], [IDPARTICIPANT] ) VALUES ( 1 , 1, 1)
go
*/