CREATE TABLE HOTELCHAMBREPRIX (
ID int IDENTITY(1,1),
IDHOTEL int NOT NULL,
IDCATEGORIECHAMBRE int NOT NULL,
PRIX float NOT NULL,
PRIMARY KEY (ID,IDHOTEL,IDCATEGORIECHAMBRE),
FOREIGN KEY (IDHOTEL) REFERENCES HOTEL(CODEHOTEL),
FOREIGN KEY (IDCATEGORIECHAMBRE) REFERENCES CATEGORIECHAMBRE(ID)
)